#!/bin/bash -e

#Have to install as postinstall is broken on 0.12.7 on Ubuntu
npm install babel-cli
npm install babel-preset-es2015
npm install babel-preset-stage-0

if [ -e bin ]; then
	echo "Do not need to create a bin dir"
else
    mkdir bin
fi

if [ ! -z ${Z3_WEB} ]; then
	echo "Em Build"
	./scripts/get_emscripten
	./scripts/build_z3
else
	echo "DllBuild"
	./scripts/build_z3_std
fi

./scripts/binds

if [ ! -z ${Z3_WEB} ]; then
	echo "Em Build Cp"
	cp ./bin/z3_bindings_em_es5.js ./bin/package.js
else
	echo "DllBuild Cp"
	cp ./bin/z3_bindings_ref_es5.js ./bin/package.js
fi


echo "Done Z3JS"

exit 0
