#!/bin/bash -e

if [ -e bin ]; then
	echo "Do not need to create a bin dir"
else
    mkdir bin
fi

if [ ! -z ${Z3_WEB} ]; then
	echo "Em Build"
	./scripts/get_emscripten
	./scripts/build_z3
else
	echo "DllBuild"
	./scripts/build_z3_std
fi

./scripts/binds

exit 0