#!/bin/bash -e
#Copyright Blake Loring <blake_l@parsed.uk> 2015

cd z3

if [ -e build ]; then
    rm -rf ./build/
fi

CC=clang CXX=clang++ python scripts/mk_make.py
(cd ../ && ./scripts/copy_bindings)
cd build

make -j 8
cp libz3* ../../bin/
