#!/bin/bash -e
cd z3

if [ -e build ]; then
    rm -rf ./build/
fi

CXX=clang++ CC=clang python scripts/mk_make.py --x86 --githash=$(git rev-parse HEAD) --staticlib
cd build

make -j 8
cp libz3* ../../compiled/