#!/bin/bash -e
entry="$(cat ./templates/pre_ref_bindings.js)"
binding="$(cat ./bin/z3_bindings_built.js)"
exit="$(cat ./templates/post_ref_bindings.js)"

printf "$entry \n\n$binding \n\n$exit" > ./bin/z3_bindings_ref.js