#!/bin/bash -e
#Copyright Blake Loring <blake_l@parsed.uk> 2015

entry="$(cat ./templates/pre_bindings.js)"
binding="$(cat ./bin/z3_bindings_stripped.js)"
exit="$(cat ./templates/post_bindings.js)"

printf "$entry \n\n$binding \n\n$exit" > ./bin/z3_bindings_built.js